-- eSlate SQLite dump (generated by api/database/dump-to-sql.php)
-- Generated: 2026-05-22T00:12:13+00:00
-- Restore with: sqlite3 database.sqlite < dump.sql

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

-- ============================ SCHEMA ============================

DROP table IF EXISTS "academic_terms";
CREATE TABLE "academic_terms" ("id" integer primary key autoincrement not null, "academic_year_id" integer not null, "term_number" integer not null, "name" varchar not null, "start_date" date not null, "end_date" date not null, "is_manually_edited" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("academic_year_id") references "academic_years"("id") on delete cascade);

DROP table IF EXISTS "academic_years";
CREATE TABLE "academic_years" ("id" integer primary key autoincrement not null, "business_id" integer not null, "state_code" varchar not null, "year" integer not null, "pack_version" varchar, "status" varchar not null default 'draft', "start_date" date not null, "end_date" date not null, "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade);

DROP table IF EXISTS "assignment_students";
CREATE TABLE "assignment_students" ("assignment_id" integer not null, "student_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("assignment_id") references "assignments"("id") on delete cascade, foreign key("student_id") references "students"("id") on delete cascade, primary key ("assignment_id", "student_id"));

DROP table IF EXISTS "assignments";
CREATE TABLE "assignments" ("id" integer primary key autoincrement not null, "business_id" integer not null, "tutor_id" integer not null, "class_id" integer, "week_id" integer, "title" varchar not null, "description" text, "pdf_path" varchar not null, "pdf_original_name" varchar not null, "due_date" date, "status" varchar not null default ('draft'), "created_at" datetime, "updated_at" datetime, "course_offering_id" integer, "course_component_id" integer, foreign key("week_id") references weeks("id") on delete set null on update no action, foreign key("class_id") references classes("id") on delete cascade on update no action, foreign key("tutor_id") references tutors("id") on delete cascade on update no action, foreign key("business_id") references businesses("id") on delete cascade on update no action, foreign key("course_offering_id") references "course_offerings"("id") on delete set null, foreign key("course_component_id") references "course_components"("id") on delete set null);

DROP table IF EXISTS "audit_log";
CREATE TABLE "audit_log" ("id" integer primary key autoincrement not null, "business_id" integer, "actor_user_id" integer, "event" varchar not null, "entity_type" varchar, "entity_id" integer, "payload" text, "occurred_at" datetime not null default CURRENT_TIMESTAMP, "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade, foreign key("actor_user_id") references "users"("id") on delete set null);

DROP table IF EXISTS "business_subjects";
CREATE TABLE "business_subjects" ("id" integer primary key autoincrement not null, "business_id" integer not null, "subject_id" integer, "name" varchar, "name_normalized" varchar, "year_levels" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade, foreign key("subject_id") references "subjects"("id") on delete cascade);

DROP table IF EXISTS "businesses";
CREATE TABLE "businesses" ("id" integer primary key autoincrement not null, "type" varchar not null, "name" varchar not null, "legal_name" varchar, "logo" varchar, "abn" varchar, "state_code" varchar not null, "timezone" varchar not null default 'Australia/Sydney', "currency" varchar not null default 'AUD', "tier" varchar not null default 'individual', "pack_version" varchar, "owner_user_id" integer, "created_at" datetime, "updated_at" datetime, foreign key("owner_user_id") references "users"("id") on delete set null);

DROP table IF EXISTS "cache";
CREATE TABLE "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));

DROP table IF EXISTS "cache_locks";
CREATE TABLE "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));

DROP table IF EXISTS "class_subjects";
CREATE TABLE "class_subjects" ("id" integer primary key autoincrement not null, "class_id" integer not null, "subject_id" integer not null, "is_primary" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("class_id") references "classes"("id") on delete cascade, foreign key("subject_id") references "subjects"("id") on delete restrict);

DROP table IF EXISTS "class_terms";
CREATE TABLE "class_terms" ("id" integer primary key autoincrement not null, "class_id" integer not null, "academic_term_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("class_id") references "classes"("id") on delete cascade, foreign key("academic_term_id") references "academic_terms"("id") on delete cascade);

DROP table IF EXISTS "classes";
CREATE TABLE "classes" ("id" integer primary key autoincrement not null, "business_id" integer not null, "tutor_id" integer, "academic_year_id" integer not null, "year_group_id" integer not null, "subject_id" integer not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime, "course_offering_id" integer, "course_id" integer, "starts_on" date, "ends_on" date, "capacity" integer, "status" varchar not null default ('draft'), "description" text, "level" varchar, "schedule_day_of_week" integer, "schedule_start_time" time, "schedule_end_time" time, "location" varchar, foreign key("course_id") references courses("id") on delete set null on update no action, foreign key("subject_id") references subjects("id") on delete restrict on update no action, foreign key("year_group_id") references year_groups("id") on delete restrict on update no action, foreign key("academic_year_id") references academic_years("id") on delete cascade on update no action, foreign key("tutor_id") references tutors("id") on delete cascade on update no action, foreign key("business_id") references businesses("id") on delete cascade on update no action, foreign key("course_offering_id") references course_offerings("id") on delete set null on update no action);

DROP table IF EXISTS "course_components";
CREATE TABLE "course_components" ("id" integer primary key autoincrement not null, "course_template_id" integer not null, "code" varchar not null, "name" varchar not null, "weight_pct" numeric, "duration_minutes" integer, "question_count" integer, "question_format" varchar not null, "sort_order" integer not null, "pack_version" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("course_template_id") references "course_templates"("id") on delete cascade);

DROP table IF EXISTS "course_offerings";
CREATE TABLE "course_offerings" ("id" integer primary key autoincrement not null, "business_id" integer not null, "course_template_id" integer, "tutor_id" integer not null, "academic_year_id" integer, "created_by_user_id" integer not null, "name" varchar not null, "target_test_date" date, "starts_on" date not null, "ends_on" date not null, "capacity" integer, "status" varchar not null default ('draft'), "notes" text, "created_at" datetime, "updated_at" datetime, "description" text, "course_id" integer, "year_group_id" integer, "subject_id" integer, "level" varchar, foreign key("business_id") references businesses("id") on delete cascade on update no action, foreign key("course_template_id") references course_templates("id") on delete no action on update no action, foreign key("tutor_id") references tutors("id") on delete cascade on update no action, foreign key("academic_year_id") references academic_years("id") on delete set null on update no action, foreign key("created_by_user_id") references users("id") on delete no action on update no action, foreign key("course_id") references "courses"("id") on delete set null, foreign key("year_group_id") references "year_groups"("id") on delete set null, foreign key("subject_id") references "subjects"("id") on delete set null);

DROP table IF EXISTS "course_subjects";
CREATE TABLE "course_subjects" ("id" integer primary key autoincrement not null, "course_id" integer not null, "subject_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("course_id") references "courses"("id") on delete cascade, foreign key("subject_id") references "subjects"("id") on delete restrict);

DROP table IF EXISTS "course_templates";
CREATE TABLE "course_templates" ("id" integer primary key autoincrement not null, "state_code" varchar not null, "year_group_code" varchar not null, "kind" varchar not null, "test_alignment" varchar, "code" varchar not null, "name" varchar not null, "short_name" varchar not null, "description" text, "sort_order" integer not null, "pack_version" varchar not null, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);

DROP table IF EXISTS "courses";
CREATE TABLE "courses" ("id" integer primary key autoincrement not null, "business_id" integer not null, "name" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade);

DROP table IF EXISTS "failed_jobs";
CREATE TABLE "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);

DROP table IF EXISTS "invitations";
CREATE TABLE "invitations" ("id" integer primary key autoincrement not null, "kind" varchar not null, "business_id" integer not null, "email" varchar not null, "first_name" varchar, "last_name" varchar, "token" varchar not null, "expires_at" datetime not null, "accepted_at" datetime, "accepted_by_user_id" integer, "revoked_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade, foreign key("accepted_by_user_id") references "users"("id") on delete set null);

DROP table IF EXISTS "job_batches";
CREATE TABLE "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));

DROP table IF EXISTS "jobs";
CREATE TABLE "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);

DROP table IF EXISTS "migrations";
CREATE TABLE "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);

DROP table IF EXISTS "offering_enrolments";
CREATE TABLE "offering_enrolments" ("id" integer primary key autoincrement not null, "business_id" integer not null, "course_offering_id" integer not null, "student_id" integer not null, "status" varchar not null, "enrolled_at" datetime not null, "withdrew_at" datetime, "completed_at" datetime, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade, foreign key("course_offering_id") references "course_offerings"("id") on delete cascade, foreign key("student_id") references "students"("id") on delete cascade);

DROP table IF EXISTS "password_reset_tokens";
CREATE TABLE "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));

DROP table IF EXISTS "personal_access_tokens";
CREATE TABLE "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" text not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);

DROP table IF EXISTS "sessions";
CREATE TABLE "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));

DROP table IF EXISTS "student_class_assignments";
CREATE TABLE "student_class_assignments" ("student_id" integer not null, "class_id" integer not null, "enrolled_at" datetime not null default CURRENT_TIMESTAMP, "created_at" datetime, "updated_at" datetime, foreign key("student_id") references "students"("id") on delete cascade, foreign key("class_id") references "classes"("id") on delete cascade, primary key ("student_id", "class_id"));

DROP table IF EXISTS "student_parents";
CREATE TABLE "student_parents" ("id" integer primary key autoincrement not null, "student_id" integer not null, "name" varchar not null, "relationship" varchar, "email" varchar, "phone" varchar, "is_primary" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("student_id") references "students"("id") on delete cascade);

DROP table IF EXISTS "student_tutors";
CREATE TABLE "student_tutors" ("id" integer primary key autoincrement not null, "business_id" integer not null, "student_id" integer not null, "tutor_id" integer not null, "subject_id" integer not null, "is_primary" tinyint(1) not null default '0', "started_at" date not null, "ended_at" date, "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade, foreign key("student_id") references "students"("id") on delete cascade, foreign key("tutor_id") references "tutors"("id") on delete cascade, foreign key("subject_id") references "subjects"("id") on delete restrict);

DROP table IF EXISTS "students";
CREATE TABLE "students" ("id" integer primary key autoincrement not null, "business_id" integer not null, "user_id" integer, "first_name" varchar not null, "last_name" varchar not null, "date_of_birth" date, "year_group_code" varchar not null, "school" varchar, "learning_goals" text, "special_needs_notes" text, "status" varchar not null default 'active', "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);

DROP table IF EXISTS "subjects";
CREATE TABLE "subjects" ("id" integer primary key autoincrement not null, "state_code" varchar not null, "code" varchar not null, "name" varchar not null, "year_levels" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);

DROP table IF EXISTS "submissions";
CREATE TABLE "submissions" ("id" integer primary key autoincrement not null, "assignment_id" integer not null, "student_id" integer not null, "status" varchar not null default 'draft', "annotated_pdf_path" varchar, "annotated_pdf_original_name" varchar, "submitted_at" datetime, "marked_at" datetime, "marked_by_tutor_id" integer, "mark_comment" text, "mark_score" numeric, "created_at" datetime, "updated_at" datetime, foreign key("assignment_id") references "assignments"("id") on delete cascade, foreign key("student_id") references "students"("id") on delete cascade, foreign key("marked_by_tutor_id") references "tutors"("id") on delete set null);

DROP table IF EXISTS "tutors";
CREATE TABLE "tutors" ("id" integer primary key autoincrement not null, "user_id" integer not null, "business_id" integer not null, "status" varchar not null default 'pending_compliance', "wwcc_number" text, "wwcc_expiry" date, "wwcc_state" varchar, "compliance_status" varchar not null default 'pending_compliance', "bio" text, "hourly_rate" numeric, "qualifications" text, "delivery_modes" text, "year_levels" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("business_id") references "businesses"("id") on delete cascade);

DROP table IF EXISTS "users";
CREATE TABLE "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "role" varchar not null default 'student');

DROP table IF EXISTS "waitlist";
CREATE TABLE "waitlist" ("id" integer primary key autoincrement not null, "email" varchar not null, "first_name" varchar, "last_name" varchar, "country" varchar not null default 'AU', "state" varchar not null, "intended_role" varchar, "notified_at" datetime, "created_at" datetime, "updated_at" datetime);

DROP table IF EXISTS "weeks";
CREATE TABLE "weeks" ("id" integer primary key autoincrement not null, "business_id" integer not null, "academic_term_id" integer not null, "week_number" integer not null, "start_date" date not null, "end_date" date not null, "is_partial" tinyint(1) not null default '0', "start_dow" integer, "public_holidays" text, "pupil_free_days" text, "notes" text, "created_at" datetime, "updated_at" datetime, foreign key("business_id") references "businesses"("id") on delete cascade, foreign key("academic_term_id") references "academic_terms"("id") on delete cascade);

DROP table IF EXISTS "year_groups";
CREATE TABLE "year_groups" ("id" integer primary key autoincrement not null, "state_code" varchar not null, "order" integer not null, "label" varchar not null, "code" varchar not null, "created_at" datetime, "updated_at" datetime);

DROP index IF EXISTS "academic_terms_academic_year_id_term_number_unique";
CREATE UNIQUE INDEX "academic_terms_academic_year_id_term_number_unique" on "academic_terms" ("academic_year_id", "term_number");

DROP index IF EXISTS "academic_years_business_id_index";
CREATE INDEX "academic_years_business_id_index" on "academic_years" ("business_id");

DROP index IF EXISTS "academic_years_business_id_year_unique";
CREATE UNIQUE INDEX "academic_years_business_id_year_unique" on "academic_years" ("business_id", "year");

DROP index IF EXISTS "academic_years_state_code_index";
CREATE INDEX "academic_years_state_code_index" on "academic_years" ("state_code");

DROP index IF EXISTS "assignment_students_student_id_index";
CREATE INDEX "assignment_students_student_id_index" on "assignment_students" ("student_id");

DROP index IF EXISTS "assignments_class_id_status_index";
CREATE INDEX "assignments_class_id_status_index" on "assignments" ("class_id", "status");

DROP index IF EXISTS "assignments_course_component_id_index";
CREATE INDEX "assignments_course_component_id_index" on "assignments" ("course_component_id");

DROP index IF EXISTS "assignments_course_offering_id_status_index";
CREATE INDEX "assignments_course_offering_id_status_index" on "assignments" ("course_offering_id", "status");

DROP index IF EXISTS "assignments_tutor_id_status_index";
CREATE INDEX "assignments_tutor_id_status_index" on "assignments" ("tutor_id", "status");

DROP index IF EXISTS "assignments_week_id_index";
CREATE INDEX "assignments_week_id_index" on "assignments" ("week_id");

DROP index IF EXISTS "audit_log_business_id_index";
CREATE INDEX "audit_log_business_id_index" on "audit_log" ("business_id");

DROP index IF EXISTS "audit_log_entity_type_entity_id_index";
CREATE INDEX "audit_log_entity_type_entity_id_index" on "audit_log" ("entity_type", "entity_id");

DROP index IF EXISTS "audit_log_event_index";
CREATE INDEX "audit_log_event_index" on "audit_log" ("event");

DROP index IF EXISTS "business_master_subject_unique";
CREATE UNIQUE INDEX "business_master_subject_unique" on "business_subjects" ("business_id", "subject_id");

DROP index IF EXISTS "business_subjects_business_id_index";
CREATE INDEX "business_subjects_business_id_index" on "business_subjects" ("business_id");

DROP index IF EXISTS "business_subjects_name_normalized_index";
CREATE INDEX "business_subjects_name_normalized_index" on "business_subjects" ("name_normalized");

DROP index IF EXISTS "business_subjects_subject_id_index";
CREATE INDEX "business_subjects_subject_id_index" on "business_subjects" ("subject_id");

DROP index IF EXISTS "businesses_owner_user_id_index";
CREATE INDEX "businesses_owner_user_id_index" on "businesses" ("owner_user_id");

DROP index IF EXISTS "businesses_state_code_index";
CREATE INDEX "businesses_state_code_index" on "businesses" ("state_code");

DROP index IF EXISTS "businesses_type_index";
CREATE INDEX "businesses_type_index" on "businesses" ("type");

DROP index IF EXISTS "cache_expiration_index";
CREATE INDEX "cache_expiration_index" on "cache" ("expiration");

DROP index IF EXISTS "cache_locks_expiration_index";
CREATE INDEX "cache_locks_expiration_index" on "cache_locks" ("expiration");

DROP index IF EXISTS "class_subjects_class_id_index";
CREATE INDEX "class_subjects_class_id_index" on "class_subjects" ("class_id");

DROP index IF EXISTS "class_subjects_class_id_subject_id_unique";
CREATE UNIQUE INDEX "class_subjects_class_id_subject_id_unique" on "class_subjects" ("class_id", "subject_id");

DROP index IF EXISTS "class_terms_academic_term_id_index";
CREATE INDEX "class_terms_academic_term_id_index" on "class_terms" ("academic_term_id");

DROP index IF EXISTS "class_terms_class_id_academic_term_id_unique";
CREATE UNIQUE INDEX "class_terms_class_id_academic_term_id_unique" on "class_terms" ("class_id", "academic_term_id");

DROP index IF EXISTS "classes_business_id_index";
CREATE INDEX "classes_business_id_index" on "classes" ("business_id");

DROP index IF EXISTS "classes_course_id_status_index";
CREATE INDEX "classes_course_id_status_index" on "classes" ("course_id", "status");

DROP index IF EXISTS "classes_course_offering_id_index";
CREATE INDEX "classes_course_offering_id_index" on "classes" ("course_offering_id");

DROP index IF EXISTS "classes_schedule_day_of_week_schedule_start_time_index";
CREATE INDEX "classes_schedule_day_of_week_schedule_start_time_index" on "classes" ("schedule_day_of_week", "schedule_start_time");

DROP index IF EXISTS "classes_status_index";
CREATE INDEX "classes_status_index" on "classes" ("status");

DROP index IF EXISTS "classes_tutor_id_index";
CREATE INDEX "classes_tutor_id_index" on "classes" ("tutor_id");

DROP index IF EXISTS "classes_tutor_id_schedule_day_of_week_index";
CREATE INDEX "classes_tutor_id_schedule_day_of_week_index" on "classes" ("tutor_id", "schedule_day_of_week");

DROP index IF EXISTS "course_components_course_template_id_code_unique";
CREATE UNIQUE INDEX "course_components_course_template_id_code_unique" on "course_components" ("course_template_id", "code");

DROP index IF EXISTS "course_offerings_business_id_status_index";
CREATE INDEX "course_offerings_business_id_status_index" on "course_offerings" ("business_id", "status");

DROP index IF EXISTS "course_offerings_course_id_year_group_id_index";
CREATE INDEX "course_offerings_course_id_year_group_id_index" on "course_offerings" ("course_id", "year_group_id");

DROP index IF EXISTS "course_offerings_course_template_id_index";
CREATE INDEX "course_offerings_course_template_id_index" on "course_offerings" ("course_template_id");

DROP index IF EXISTS "course_offerings_tutor_id_status_index";
CREATE INDEX "course_offerings_tutor_id_status_index" on "course_offerings" ("tutor_id", "status");

DROP index IF EXISTS "course_subjects_course_id_index";
CREATE INDEX "course_subjects_course_id_index" on "course_subjects" ("course_id");

DROP index IF EXISTS "course_subjects_course_id_subject_id_unique";
CREATE UNIQUE INDEX "course_subjects_course_id_subject_id_unique" on "course_subjects" ("course_id", "subject_id");

DROP index IF EXISTS "course_templates_code_unique";
CREATE UNIQUE INDEX "course_templates_code_unique" on "course_templates" ("code");

DROP index IF EXISTS "course_templates_state_code_year_group_code_index";
CREATE INDEX "course_templates_state_code_year_group_code_index" on "course_templates" ("state_code", "year_group_code");

DROP index IF EXISTS "course_templates_state_year_kind_align_unique";
CREATE UNIQUE INDEX "course_templates_state_year_kind_align_unique" on "course_templates" ("state_code", "year_group_code", "kind", "test_alignment");

DROP index IF EXISTS "courses_business_id_name_index";
CREATE INDEX "courses_business_id_name_index" on "courses" ("business_id", "name");

DROP index IF EXISTS "failed_jobs_uuid_unique";
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");

DROP index IF EXISTS "invitations_business_id_index";
CREATE INDEX "invitations_business_id_index" on "invitations" ("business_id");

DROP index IF EXISTS "invitations_email_index";
CREATE INDEX "invitations_email_index" on "invitations" ("email");

DROP index IF EXISTS "invitations_kind_business_id_index";
CREATE INDEX "invitations_kind_business_id_index" on "invitations" ("kind", "business_id");

DROP index IF EXISTS "invitations_token_unique";
CREATE UNIQUE INDEX "invitations_token_unique" on "invitations" ("token");

DROP index IF EXISTS "jobs_queue_index";
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");

DROP index IF EXISTS "offering_enrolments_business_id_status_index";
CREATE INDEX "offering_enrolments_business_id_status_index" on "offering_enrolments" ("business_id", "status");

DROP index IF EXISTS "offering_enrolments_course_offering_id_status_index";
CREATE INDEX "offering_enrolments_course_offering_id_status_index" on "offering_enrolments" ("course_offering_id", "status");

DROP index IF EXISTS "offering_enrolments_one_active_per_student";
CREATE UNIQUE INDEX offering_enrolments_one_active_per_student ON offering_enrolments (course_offering_id, student_id) WHERE status = 'active';

DROP index IF EXISTS "offering_enrolments_student_id_index";
CREATE INDEX "offering_enrolments_student_id_index" on "offering_enrolments" ("student_id");

DROP index IF EXISTS "personal_access_tokens_expires_at_index";
CREATE INDEX "personal_access_tokens_expires_at_index" on "personal_access_tokens" ("expires_at");

DROP index IF EXISTS "personal_access_tokens_token_unique";
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");

DROP index IF EXISTS "personal_access_tokens_tokenable_type_tokenable_id_index";
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");

DROP index IF EXISTS "sessions_last_activity_index";
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");

DROP index IF EXISTS "sessions_user_id_index";
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");

DROP index IF EXISTS "student_class_assignments_class_id_index";
CREATE INDEX "student_class_assignments_class_id_index" on "student_class_assignments" ("class_id");

DROP index IF EXISTS "student_parents_student_id_index";
CREATE INDEX "student_parents_student_id_index" on "student_parents" ("student_id");

DROP index IF EXISTS "student_tutor_subject_unique";
CREATE UNIQUE INDEX "student_tutor_subject_unique" on "student_tutors" ("student_id", "subject_id", "tutor_id");

DROP index IF EXISTS "student_tutors_one_primary_per_subject";
CREATE UNIQUE INDEX student_tutors_one_primary_per_subject
                 ON student_tutors (student_id, subject_id) WHERE is_primary = 1;

DROP index IF EXISTS "student_tutors_student_id_subject_id_index";
CREATE INDEX "student_tutors_student_id_subject_id_index" on "student_tutors" ("student_id", "subject_id");

DROP index IF EXISTS "student_tutors_tutor_id_index";
CREATE INDEX "student_tutors_tutor_id_index" on "student_tutors" ("tutor_id");

DROP index IF EXISTS "students_business_id_index";
CREATE INDEX "students_business_id_index" on "students" ("business_id");

DROP index IF EXISTS "students_status_index";
CREATE INDEX "students_status_index" on "students" ("status");

DROP index IF EXISTS "students_user_id_unique";
CREATE UNIQUE INDEX "students_user_id_unique" on "students" ("user_id");

DROP index IF EXISTS "students_year_group_code_index";
CREATE INDEX "students_year_group_code_index" on "students" ("year_group_code");

DROP index IF EXISTS "subjects_state_code_code_unique";
CREATE UNIQUE INDEX "subjects_state_code_code_unique" on "subjects" ("state_code", "code");

DROP index IF EXISTS "subjects_state_code_index";
CREATE INDEX "subjects_state_code_index" on "subjects" ("state_code");

DROP index IF EXISTS "submissions_assignment_id_status_index";
CREATE INDEX "submissions_assignment_id_status_index" on "submissions" ("assignment_id", "status");

DROP index IF EXISTS "submissions_assignment_id_student_id_unique";
CREATE UNIQUE INDEX "submissions_assignment_id_student_id_unique" on "submissions" ("assignment_id", "student_id");

DROP index IF EXISTS "submissions_student_id_status_index";
CREATE INDEX "submissions_student_id_status_index" on "submissions" ("student_id", "status");

DROP index IF EXISTS "tutors_business_id_index";
CREATE INDEX "tutors_business_id_index" on "tutors" ("business_id");

DROP index IF EXISTS "tutors_compliance_status_index";
CREATE INDEX "tutors_compliance_status_index" on "tutors" ("compliance_status");

DROP index IF EXISTS "tutors_status_index";
CREATE INDEX "tutors_status_index" on "tutors" ("status");

DROP index IF EXISTS "tutors_user_id_unique";
CREATE UNIQUE INDEX "tutors_user_id_unique" on "tutors" ("user_id");

DROP index IF EXISTS "users_email_unique";
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");

DROP index IF EXISTS "waitlist_email_index";
CREATE INDEX "waitlist_email_index" on "waitlist" ("email");

DROP index IF EXISTS "waitlist_state_index";
CREATE INDEX "waitlist_state_index" on "waitlist" ("state");

DROP index IF EXISTS "weeks_academic_term_id_week_number_unique";
CREATE UNIQUE INDEX "weeks_academic_term_id_week_number_unique" on "weeks" ("academic_term_id", "week_number");

DROP index IF EXISTS "weeks_business_id_index";
CREATE INDEX "weeks_business_id_index" on "weeks" ("business_id");

DROP index IF EXISTS "year_groups_state_code_code_unique";
CREATE UNIQUE INDEX "year_groups_state_code_code_unique" on "year_groups" ("state_code", "code");

DROP index IF EXISTS "year_groups_state_code_order_unique";
CREATE UNIQUE INDEX "year_groups_state_code_order_unique" on "year_groups" ("state_code", "order");


-- ============================ DATA ============================

-- course_components (70 rows)
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (1,1,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (2,2,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (3,3,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (4,4,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (5,5,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (6,6,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (7,7,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (8,8,'reading','Reading',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (9,8,'writing','Writing',NULL,NULL,NULL,'free_response_writing',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (10,8,'conventions_of_language','Conventions of Language',NULL,NULL,NULL,'cloze',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (11,8,'numeracy','Numeracy',NULL,NULL,NULL,'mixed',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (12,9,'reading','Reading',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (13,9,'writing','Writing',NULL,NULL,NULL,'free_response_writing',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (14,9,'conventions_of_language','Conventions of Language',NULL,NULL,NULL,'cloze',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (15,9,'numeracy','Numeracy',NULL,NULL,NULL,'mixed',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (16,10,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (17,11,'reading','Reading',33.33,30,25,'multi_part_mcq',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (18,11,'maths_reasoning','Mathematical Reasoning',33.33,40,35,'multiple_choice',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (19,11,'thinking_skills','Thinking Skills',33.34,30,30,'multiple_choice',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (20,12,'reading','Reading',33.33,30,25,'multi_part_mcq',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (21,12,'maths_reasoning','Mathematical Reasoning',33.33,40,35,'multiple_choice',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (22,12,'thinking_skills','Thinking Skills',33.34,30,30,'multiple_choice',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (23,13,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (24,14,'reading','Reading',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (25,14,'writing','Writing',NULL,NULL,NULL,'free_response_writing',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (26,14,'conventions_of_language','Conventions of Language',NULL,NULL,NULL,'cloze',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (27,14,'numeracy','Numeracy',NULL,NULL,NULL,'mixed',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (28,15,'reading','Reading',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (29,15,'writing','Writing',NULL,NULL,NULL,'free_response_writing',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (30,15,'conventions_of_language','Conventions of Language',NULL,NULL,NULL,'cloze',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (31,15,'numeracy','Numeracy',NULL,NULL,NULL,'mixed',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (32,16,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (33,17,'reading','Reading',25,40,NULL,'multi_part_mcq',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (34,17,'maths_reasoning','Mathematical Reasoning',25,40,NULL,'multiple_choice',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (35,17,'thinking_skills','Thinking Skills',25,40,NULL,'multiple_choice',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (36,17,'writing','Writing',25,30,NULL,'free_response_writing',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (37,18,'reading','Reading',25,40,NULL,'multi_part_mcq',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (38,18,'maths_reasoning','Mathematical Reasoning',25,40,NULL,'multiple_choice',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (39,18,'thinking_skills','Thinking Skills',25,40,NULL,'multiple_choice',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (40,18,'writing','Writing',25,30,NULL,'free_response_writing',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (41,19,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (42,20,'reading','Reading',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (43,20,'writing','Writing',NULL,NULL,NULL,'free_response_writing',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (44,20,'conventions_of_language','Conventions of Language',NULL,NULL,NULL,'cloze',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (45,20,'numeracy','Numeracy',NULL,NULL,NULL,'mixed',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (46,21,'reading','Reading',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (47,21,'writing','Writing',NULL,NULL,NULL,'free_response_writing',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (48,21,'conventions_of_language','Conventions of Language',NULL,NULL,NULL,'cloze',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (49,21,'numeracy','Numeracy',NULL,NULL,NULL,'mixed',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (50,22,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (51,23,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (52,24,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (53,25,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (54,26,'reading','Reading',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (55,26,'writing','Writing',NULL,NULL,NULL,'free_response_writing',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (56,26,'conventions_of_language','Conventions of Language',NULL,NULL,NULL,'cloze',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (57,26,'numeracy','Numeracy',NULL,NULL,NULL,'mixed',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (58,27,'reading','Reading',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (59,27,'writing','Writing',NULL,NULL,NULL,'free_response_writing',1,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (60,27,'conventions_of_language','Conventions of Language',NULL,NULL,NULL,'cloze',2,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (61,27,'numeracy','Numeracy',NULL,NULL,NULL,'mixed',3,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (62,28,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (63,29,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (64,30,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (65,31,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (66,32,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (67,33,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (68,34,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (69,35,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_components" ("id","course_template_id","code","name","weight_pct","duration_minutes","question_count","question_format","sort_order","pack_version","created_at","updated_at") VALUES (70,36,'general','General',NULL,NULL,NULL,'mixed',0,'1.0.0','2026-05-12 04:06:41','2026-05-12 04:06:41');

-- course_templates (36 rows)
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (1,'NSW','K','foundations',NULL,'nsw_yk_foundations','Kindergarten Foundations','K Foundations','Foundational skills for Kindergarten students. Year-appropriate content not tied to any specific test.',0,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (2,'NSW','K','theory',NULL,'nsw_yk_wemt','Kindergarten WEMT (Theory)','K WEMT','Weekly theory for Kindergarten students. General year-level content.',1,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (3,'NSW','Y1','foundations',NULL,'nsw_y1_foundations','Year 1 Foundations','Y1 Foundations','Foundational skills for Year 1 students. Year-appropriate content not tied to any specific test.',10,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (4,'NSW','Y1','theory',NULL,'nsw_y1_wemt','Year 1 WEMT (Theory)','Y1 WEMT','Weekly theory for Year 1 students. General year-level content.',11,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (5,'NSW','Y2','foundations',NULL,'nsw_y2_foundations','Year 2 Foundations','Y2 Foundations','Foundational skills for Year 2 students. Year-appropriate content not tied to any specific test.',20,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (6,'NSW','Y2','theory',NULL,'nsw_y2_wemt','Year 2 WEMT (Theory)','Y2 WEMT','Weekly theory for Year 2 students. General year-level content.',21,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (7,'NSW','Y3','foundations',NULL,'nsw_y3_foundations','Year 3 Foundations','Y3 Foundations','Foundational skills for Year 3 students. Year-appropriate content not tied to any specific test.',30,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (8,'NSW','Y3','theory','naplan_y3','nsw_y3_wemt','Year 3 NAPLAN WEMT (Theory)','Y3 NAPLAN WEMT','Theory and practice for the Year 3 NAPLAN assessment. Four domains: Reading, Writing, Conventions of Language, Numeracy.',31,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (9,'NSW','Y3','mock_tests','naplan_y3','nsw_y3_mock_tests','Year 3 NAPLAN Mock Tests','Y3 NAPLAN Mock','Mock NAPLAN tests in the four NAPLAN domains for Year 3.',32,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (10,'NSW','Y4','foundations',NULL,'nsw_y4_foundations','Year 4 Foundations','Y4 Foundations','Foundational skills for Year 4 students. Year-appropriate content not tied to any specific test.',40,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (11,'NSW','Y4','theory','oc','nsw_y4_wemt','Year 4 OC WEMT (Theory)','Y4 OC WEMT','Theory and practice for the NSW Opportunity Class Placement Test. Three sections: Reading, Mathematical Reasoning, Thinking Skills.',41,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (12,'NSW','Y4','mock_tests','oc','nsw_y4_mock_tests','Year 4 OCTT (OC Mock Tests)','Y4 OCTT','Mock OC Placement Tests in the same section structure as the real test.',42,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (13,'NSW','Y5','foundations',NULL,'nsw_y5_foundations','Year 5 Foundations','Y5 Foundations','Foundational skills for Year 5 students. Year-appropriate content not tied to any specific test.',50,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (14,'NSW','Y5','theory','naplan_y5','nsw_y5_wemt','Year 5 NAPLAN WEMT (Theory)','Y5 NAPLAN WEMT','Theory and practice for the Year 5 NAPLAN assessment. Four domains: Reading, Writing, Conventions of Language, Numeracy.',51,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (15,'NSW','Y5','mock_tests','naplan_y5','nsw_y5_mock_tests','Year 5 NAPLAN Mock Tests','Y5 NAPLAN Mock','Mock NAPLAN tests in the four NAPLAN domains for Year 5.',52,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (16,'NSW','Y6','foundations',NULL,'nsw_y6_foundations','Year 6 Foundations','Y6 Foundations','Foundational skills for Year 6 students. Year-appropriate content not tied to any specific test.',60,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (17,'NSW','Y6','theory','selective','nsw_y6_wemt','Year 6 Selective WEMT (Theory)','Y6 Selective WEMT','Theory and practice for the NSW Selective High School Placement Test. Four sections: Reading, Mathematical Reasoning, Thinking Skills, Writing.',61,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (18,'NSW','Y6','mock_tests','selective','nsw_y6_mock_tests','Year 6 STTC (Selective Mock Tests)','Y6 STTC','Mock Selective High School Placement Tests in the same section structure as the real test.',62,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (19,'NSW','Y7','foundations',NULL,'nsw_y7_foundations','Year 7 Foundations','Y7 Foundations','Foundational skills for Year 7 students. Year-appropriate content not tied to any specific test.',70,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (20,'NSW','Y7','theory','naplan_y7','nsw_y7_wemt','Year 7 NAPLAN WEMT (Theory)','Y7 NAPLAN WEMT','Theory and practice for the Year 7 NAPLAN assessment. Four domains: Reading, Writing, Conventions of Language, Numeracy.',71,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (21,'NSW','Y7','mock_tests','naplan_y7','nsw_y7_mock_tests','Year 7 NAPLAN Mock Tests','Y7 NAPLAN Mock','Mock NAPLAN tests in the four NAPLAN domains for Year 7.',72,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (22,'NSW','Y8','foundations',NULL,'nsw_y8_foundations','Year 8 Foundations','Y8 Foundations','Foundational skills for Year 8 students. Year-appropriate content not tied to any specific test.',80,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (23,'NSW','Y8','theory',NULL,'nsw_y8_wemt','Year 8 WEMT (Theory)','Y8 WEMT','Weekly theory for Year 8 students. General year-level content.',81,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (24,'NSW','Y8','mock_tests',NULL,'nsw_y8_mock_tests','Year 8 Mock Tests','Y8 Mocks','General timed practice tests for Year 8 students.',82,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (25,'NSW','Y9','foundations',NULL,'nsw_y9_foundations','Year 9 Foundations','Y9 Foundations','Foundational skills for Year 9 students. Year-appropriate content not tied to any specific test.',90,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (26,'NSW','Y9','theory','naplan_y9','nsw_y9_wemt','Year 9 NAPLAN WEMT (Theory)','Y9 NAPLAN WEMT','Theory and practice for the Year 9 NAPLAN assessment. Four domains: Reading, Writing, Conventions of Language, Numeracy.',91,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (27,'NSW','Y9','mock_tests','naplan_y9','nsw_y9_mock_tests','Year 9 NAPLAN Mock Tests','Y9 NAPLAN Mock','Mock NAPLAN tests in the four NAPLAN domains for Year 9.',92,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (28,'NSW','Y10','foundations',NULL,'nsw_y10_foundations','Year 10 Foundations','Y10 Foundations','Foundational skills for Year 10 students. Year-appropriate content not tied to any specific test.',100,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (29,'NSW','Y10','theory',NULL,'nsw_y10_wemt','Year 10 WEMT (Theory)','Y10 WEMT','Weekly theory for Year 10 students. General year-level content.',101,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (30,'NSW','Y10','mock_tests',NULL,'nsw_y10_mock_tests','Year 10 Mock Tests','Y10 Mocks','General timed practice tests for Year 10 students.',102,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (31,'NSW','Y11','foundations',NULL,'nsw_y11_foundations','Year 11 Foundations','Y11 Foundations','Foundational skills for Year 11 students. Year-appropriate content not tied to any specific test.',110,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (32,'NSW','Y11','theory',NULL,'nsw_y11_wemt','Year 11 WEMT (Theory)','Y11 WEMT','Weekly theory for Year 11 students. General year-level content.',111,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (33,'NSW','Y11','mock_tests',NULL,'nsw_y11_mock_tests','Year 11 Mock Tests','Y11 Mocks','General timed practice tests for Year 11 students.',112,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (34,'NSW','Y12','foundations',NULL,'nsw_y12_foundations','Year 12 Foundations','Y12 Foundations','Foundational skills for Year 12 students. Year-appropriate content not tied to any specific test.',120,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (35,'NSW','Y12','theory',NULL,'nsw_y12_wemt','Year 12 WEMT (Theory)','Y12 WEMT','Weekly theory for Year 12 students. General year-level content.',121,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');
INSERT INTO "course_templates" ("id","state_code","year_group_code","kind","test_alignment","code","name","short_name","description","sort_order","pack_version","is_active","created_at","updated_at") VALUES (36,'NSW','Y12','mock_tests',NULL,'nsw_y12_mock_tests','Year 12 Mock Tests','Y12 Mocks','General timed practice tests for Year 12 students.',122,'1.0.0',1,'2026-05-12 04:06:41','2026-05-12 04:06:41');

-- migrations (39 rows)
INSERT INTO "migrations" ("id","migration","batch") VALUES (1,'0001_01_01_000000_create_users_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (4,'2026_05_04_051733_create_personal_access_tokens_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (5,'2026_05_04_060001_add_role_to_users_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (6,'2026_05_04_060002_create_businesses_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (7,'2026_05_04_060003_create_tutors_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (8,'2026_05_04_060004_create_students_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (9,'2026_05_04_060005_create_student_tutors_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (10,'2026_05_04_070001_create_subjects_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (11,'2026_05_04_070002_create_year_groups_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (12,'2026_05_04_070003_create_academic_years_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (13,'2026_05_04_070004_create_academic_terms_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (14,'2026_05_04_070005_create_weeks_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (15,'2026_05_04_070006_create_classes_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (16,'2026_05_04_070007_create_student_class_assignments_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (17,'2026_05_04_080001_create_assignments_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (18,'2026_05_04_080002_create_assignment_students_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (19,'2026_05_04_080003_create_submissions_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (20,'2026_05_05_010001_create_business_subjects_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (21,'2026_05_05_010002_create_waitlist_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (22,'2026_05_05_010003_create_audit_log_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (23,'2026_05_05_020001_create_invitations_table',2);
INSERT INTO "migrations" ("id","migration","batch") VALUES (25,'2026_05_12_000001_create_student_parents_table',3);
INSERT INTO "migrations" ("id","migration","batch") VALUES (26,'2026_05_12_010001_create_course_templates_table',4);
INSERT INTO "migrations" ("id","migration","batch") VALUES (27,'2026_05_12_010002_create_course_components_table',4);
INSERT INTO "migrations" ("id","migration","batch") VALUES (28,'2026_05_12_010003_create_course_offerings_table',4);
INSERT INTO "migrations" ("id","migration","batch") VALUES (29,'2026_05_12_010004_create_offering_enrolments_table',4);
INSERT INTO "migrations" ("id","migration","batch") VALUES (30,'2026_05_12_010005_add_course_columns_to_assignments_table',4);
INSERT INTO "migrations" ("id","migration","batch") VALUES (31,'2026_05_12_020001_extend_course_offerings_for_custom_courses',5);
INSERT INTO "migrations" ("id","migration","batch") VALUES (32,'2026_05_12_020002_add_course_offering_id_to_classes_table',5);
INSERT INTO "migrations" ("id","migration","batch") VALUES (33,'2026_05_13_010001_create_courses_table',6);
INSERT INTO "migrations" ("id","migration","batch") VALUES (34,'2026_05_13_010002_add_catalogue_fields_to_course_offerings',6);
INSERT INTO "migrations" ("id","migration","batch") VALUES (35,'2026_05_14_010001_extend_classes_for_class_collapse',7);
INSERT INTO "migrations" ("id","migration","batch") VALUES (36,'2026_05_14_010002_create_class_terms_table',7);
INSERT INTO "migrations" ("id","migration","batch") VALUES (37,'2026_05_14_020001_make_class_tutor_nullable',8);
INSERT INTO "migrations" ("id","migration","batch") VALUES (38,'2026_05_15_010001_add_schedule_to_classes',9);
INSERT INTO "migrations" ("id","migration","batch") VALUES (39,'2026_05_21_113001_create_course_subjects_table',10);
INSERT INTO "migrations" ("id","migration","batch") VALUES (40,'2026_05_21_113002_create_class_subjects_table',10);

-- personal_access_tokens (7 rows)
INSERT INTO "personal_access_tokens" ("id","tokenable_type","tokenable_id","name","token","abilities","last_used_at","expires_at","created_at","updated_at") VALUES (34,'App\Models\User',18,'api-token','61b422b6bf252b95699d9248144039da106d84b2d451c42c6ae4fa44b1f6c387','["*"]',NULL,NULL,'2026-05-21 05:34:24','2026-05-21 05:34:24');
INSERT INTO "personal_access_tokens" ("id","tokenable_type","tokenable_id","name","token","abilities","last_used_at","expires_at","created_at","updated_at") VALUES (35,'App\Models\User',18,'api-token','70f7476e402745eb5ea054efb0ca37fc2a5984a9e7030dfd730495e6b7d9d0a2','["*"]',NULL,NULL,'2026-05-21 05:34:31','2026-05-21 05:34:31');
INSERT INTO "personal_access_tokens" ("id","tokenable_type","tokenable_id","name","token","abilities","last_used_at","expires_at","created_at","updated_at") VALUES (36,'App\Models\User',18,'api-token','fcde50dd004e6bf52208bee23d769ec127126182b78df31925eb10db98718212','["*"]','2026-05-21 23:57:10',NULL,'2026-05-21 23:29:16','2026-05-21 23:57:10');
INSERT INTO "personal_access_tokens" ("id","tokenable_type","tokenable_id","name","token","abilities","last_used_at","expires_at","created_at","updated_at") VALUES (37,'App\Models\User',18,'api-token','87f3949cf7a71955629589ad5343374391691523584d1ddf2177a190c6a66316','["*"]','2026-05-21 23:53:13',NULL,'2026-05-21 23:53:12','2026-05-21 23:53:13');
INSERT INTO "personal_access_tokens" ("id","tokenable_type","tokenable_id","name","token","abilities","last_used_at","expires_at","created_at","updated_at") VALUES (38,'App\Models\User',18,'api-token','97079db8816c9732740253ae707ea84ee0d48965d519ce6a5d4c08cbc121a0f7','["*"]',NULL,NULL,'2026-05-21 23:56:31','2026-05-21 23:56:31');
INSERT INTO "personal_access_tokens" ("id","tokenable_type","tokenable_id","name","token","abilities","last_used_at","expires_at","created_at","updated_at") VALUES (39,'App\Models\User',18,'api-token','a0ab12fbd2a35ff870b84ad42f331be1f5bc78847f571c343dc3156a9cc0acc1','["*"]',NULL,NULL,'2026-05-21 23:56:33','2026-05-21 23:56:33');
INSERT INTO "personal_access_tokens" ("id","tokenable_type","tokenable_id","name","token","abilities","last_used_at","expires_at","created_at","updated_at") VALUES (40,'App\Models\User',18,'api-token','ce7ddcea5f08f50ed2a9673c756e3c36dbcc741ea49e6ad0df9cd267c27225c1','["*"]','2026-05-21 23:59:22',NULL,'2026-05-21 23:57:13','2026-05-21 23:59:22');

-- subjects (6 rows)
INSERT INTO "subjects" ("id","state_code","code","name","year_levels","is_active","created_at","updated_at") VALUES (1,'NSW','MATH','Mathematics','["K","Y1","Y2","Y3","Y4","Y5","Y6"]',1,'2026-05-05 02:59:53','2026-05-21 01:20:55');
INSERT INTO "subjects" ("id","state_code","code","name","year_levels","is_active","created_at","updated_at") VALUES (4,'NSW','ENG','English','["K","Y1","Y2","Y3","Y4","Y5","Y6"]',1,'2026-05-05 02:59:53','2026-05-21 01:20:55');
INSERT INTO "subjects" ("id","state_code","code","name","year_levels","is_active","created_at","updated_at") VALUES (7,'NSW','SCI','Science','["K","Y1","Y2","Y3","Y4","Y5","Y6"]',1,'2026-05-05 02:59:53','2026-05-21 01:20:55');
INSERT INTO "subjects" ("id","state_code","code","name","year_levels","is_active","created_at","updated_at") VALUES (21,'NSW','READ','Reading','["K","Y1","Y2","Y3","Y4","Y5","Y6"]',1,'2026-05-21 01:20:55','2026-05-21 01:20:55');
INSERT INTO "subjects" ("id","state_code","code","name","year_levels","is_active","created_at","updated_at") VALUES (22,'NSW','WRITE','Writing','["K","Y1","Y2","Y3","Y4","Y5","Y6"]',1,'2026-05-21 01:20:55','2026-05-21 01:20:55');
INSERT INTO "subjects" ("id","state_code","code","name","year_levels","is_active","created_at","updated_at") VALUES (23,'NSW','THINK','Thinking Skills','["K","Y1","Y2","Y3","Y4","Y5","Y6"]',1,'2026-05-21 01:20:55','2026-05-21 01:20:55');

-- users (1 rows)
INSERT INTO "users" ("id","name","email","email_verified_at","password","remember_token","created_at","updated_at","role") VALUES (18,'eSlate Admin','admin@eslate.com',NULL,'$2y$12$OkogS6jkjXy.1RqssWF2Wunw1tScvdxfi4gLp3eMXzxniZp2fQbtG',NULL,'2026-05-21 05:34:17','2026-05-21 05:34:17','admin');

-- waitlist (1 rows)
INSERT INTO "waitlist" ("id","email","first_name","last_name","country","state","intended_role","notified_at","created_at","updated_at") VALUES (1,'vic-tutor@example.com','Vic',NULL,'AU','VIC','individual_tutor',NULL,'2026-05-05 03:41:51','2026-05-05 03:41:51');

-- year_groups (104 rows)
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (1,'NSW',0,'Kindergarten','K','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (2,'NSW',1,'Year 1','Y1','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (3,'NSW',2,'Year 2','Y2','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (4,'NSW',3,'Year 3','Y3','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (5,'NSW',4,'Year 4','Y4','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (6,'NSW',5,'Year 5','Y5','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (7,'NSW',6,'Year 6','Y6','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (8,'NSW',7,'Year 7','Y7','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (9,'NSW',8,'Year 8','Y8','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (10,'NSW',9,'Year 9','Y9','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (11,'NSW',10,'Year 10','Y10','2026-05-05 02:59:53','2026-05-05 02:59:53');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (12,'NSW',11,'Year 11','Y11','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (13,'NSW',12,'Year 12','Y12','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (14,'VIC',0,'Prep','P','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (15,'VIC',1,'Year 1','Y1','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (16,'VIC',2,'Year 2','Y2','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (17,'VIC',3,'Year 3','Y3','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (18,'VIC',4,'Year 4','Y4','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (19,'VIC',5,'Year 5','Y5','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (20,'VIC',6,'Year 6','Y6','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (21,'VIC',7,'Year 7','Y7','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (22,'VIC',8,'Year 8','Y8','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (23,'VIC',9,'Year 9','Y9','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (24,'VIC',10,'Year 10','Y10','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (25,'VIC',11,'Year 11','Y11','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (26,'VIC',12,'Year 12','Y12','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (27,'QLD',0,'Prep','P','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (28,'QLD',1,'Year 1','Y1','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (29,'QLD',2,'Year 2','Y2','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (30,'QLD',3,'Year 3','Y3','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (31,'QLD',4,'Year 4','Y4','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (32,'QLD',5,'Year 5','Y5','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (33,'QLD',6,'Year 6','Y6','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (34,'QLD',7,'Year 7','Y7','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (35,'QLD',8,'Year 8','Y8','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (36,'QLD',9,'Year 9','Y9','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (37,'QLD',10,'Year 10','Y10','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (38,'QLD',11,'Year 11','Y11','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (39,'QLD',12,'Year 12','Y12','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (40,'WA',0,'Pre-primary','PP','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (41,'WA',1,'Year 1','Y1','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (42,'WA',2,'Year 2','Y2','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (43,'WA',3,'Year 3','Y3','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (44,'WA',4,'Year 4','Y4','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (45,'WA',5,'Year 5','Y5','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (46,'WA',6,'Year 6','Y6','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (47,'WA',7,'Year 7','Y7','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (48,'WA',8,'Year 8','Y8','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (49,'WA',9,'Year 9','Y9','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (50,'WA',10,'Year 10','Y10','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (51,'WA',11,'Year 11','Y11','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (52,'WA',12,'Year 12','Y12','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (53,'SA',0,'Reception','R','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (54,'SA',1,'Year 1','Y1','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (55,'SA',2,'Year 2','Y2','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (56,'SA',3,'Year 3','Y3','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (57,'SA',4,'Year 4','Y4','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (58,'SA',5,'Year 5','Y5','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (59,'SA',6,'Year 6','Y6','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (60,'SA',7,'Year 7','Y7','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (61,'SA',8,'Year 8','Y8','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (62,'SA',9,'Year 9','Y9','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (63,'SA',10,'Year 10','Y10','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (64,'SA',11,'Year 11','Y11','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (65,'SA',12,'Year 12','Y12','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (66,'TAS',0,'Prep','P','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (67,'TAS',1,'Year 1','Y1','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (68,'TAS',2,'Year 2','Y2','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (69,'TAS',3,'Year 3','Y3','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (70,'TAS',4,'Year 4','Y4','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (71,'TAS',5,'Year 5','Y5','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (72,'TAS',6,'Year 6','Y6','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (73,'TAS',7,'Year 7','Y7','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (74,'TAS',8,'Year 8','Y8','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (75,'TAS',9,'Year 9','Y9','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (76,'TAS',10,'Year 10','Y10','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (77,'TAS',11,'Year 11','Y11','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (78,'TAS',12,'Year 12','Y12','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (79,'ACT',0,'Kindergarten','K','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (80,'ACT',1,'Year 1','Y1','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (81,'ACT',2,'Year 2','Y2','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (82,'ACT',3,'Year 3','Y3','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (83,'ACT',4,'Year 4','Y4','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (84,'ACT',5,'Year 5','Y5','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (85,'ACT',6,'Year 6','Y6','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (86,'ACT',7,'Year 7','Y7','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (87,'ACT',8,'Year 8','Y8','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (88,'ACT',9,'Year 9','Y9','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (89,'ACT',10,'Year 10','Y10','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (90,'ACT',11,'Year 11','Y11','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (91,'ACT',12,'Year 12','Y12','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (92,'NT',0,'Transition','T','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (93,'NT',1,'Year 1','Y1','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (94,'NT',2,'Year 2','Y2','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (95,'NT',3,'Year 3','Y3','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (96,'NT',4,'Year 4','Y4','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (97,'NT',5,'Year 5','Y5','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (98,'NT',6,'Year 6','Y6','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (99,'NT',7,'Year 7','Y7','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (100,'NT',8,'Year 8','Y8','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (101,'NT',9,'Year 9','Y9','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (102,'NT',10,'Year 10','Y10','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (103,'NT',11,'Year 11','Y11','2026-05-05 02:59:54','2026-05-05 02:59:54');
INSERT INTO "year_groups" ("id","state_code","order","label","code","created_at","updated_at") VALUES (104,'NT',12,'Year 12','Y12','2026-05-05 02:59:54','2026-05-05 02:59:54');

COMMIT;
PRAGMA foreign_keys=ON;
