<?php
/**
 * Dump the current SQLite dev DB to dump.sql (schema + data) so the
 * snapshot can be committed to the repo without committing the binary
 * .sqlite file. Re-run after schema or seed changes when you want to
 * refresh the committed snapshot.
 *
 * Usage:
 *   "C:/laragon/bin/php/php-8.3.30-Win32-vs16-x64/php.exe" \
 *     "C:/NT/eSlate/api/database/dump-to-sql.php"
 */

$dbPath = __DIR__ . '/database.sqlite';
$outPath = __DIR__ . '/dump.sql';

if (! file_exists($dbPath)) {
    fwrite(STDERR, "DB not found: $dbPath\n");
    exit(1);
}

$pdo = new PDO("sqlite:$dbPath");
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$out = fopen($outPath, 'w');
fwrite($out, "-- eSlate SQLite dump (generated by api/database/dump-to-sql.php)\n");
fwrite($out, "-- Generated: " . date('c') . "\n");
fwrite($out, "-- Restore with: sqlite3 database.sqlite < dump.sql\n");
fwrite($out, "\nPRAGMA foreign_keys=OFF;\nBEGIN TRANSACTION;\n\n");

// 1. Schema (CREATE statements). Skip sqlite_-prefixed internal tables.
$schemaRows = $pdo->query(
    "SELECT type, name, sql FROM sqlite_master "
    . "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
    . "ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'index' THEN 2 ELSE 3 END, name"
)->fetchAll(PDO::FETCH_ASSOC);

fwrite($out, "-- ============================ SCHEMA ============================\n\n");
foreach ($schemaRows as $r) {
    fwrite($out, "DROP {$r['type']} IF EXISTS \"{$r['name']}\";\n");
    fwrite($out, $r['sql'] . ";\n\n");
}

// 2. Data — INSERT statements per row in each user table.
$tables = $pdo->query(
    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
)->fetchAll(PDO::FETCH_COLUMN);

fwrite($out, "\n-- ============================ DATA ============================\n\n");
$totalRows = 0;
foreach ($tables as $table) {
    $rows = $pdo->query("SELECT * FROM \"$table\"")->fetchAll(PDO::FETCH_ASSOC);
    if (empty($rows)) continue;

    fwrite($out, "-- $table (" . count($rows) . " rows)\n");
    $cols = array_keys($rows[0]);
    $colsList = '"' . implode('","', $cols) . '"';

    foreach ($rows as $row) {
        $values = array_map(function ($v) use ($pdo) {
            if ($v === null) return 'NULL';
            if (is_int($v) || is_float($v)) return (string) $v;
            return $pdo->quote((string) $v);
        }, array_values($row));
        fwrite($out, "INSERT INTO \"$table\" ($colsList) VALUES (" . implode(',', $values) . ");\n");
        $totalRows++;
    }
    fwrite($out, "\n");
}

fwrite($out, "COMMIT;\nPRAGMA foreign_keys=ON;\n");
fclose($out);

echo "Wrote $outPath\n";
echo "  " . count($tables) . " tables, $totalRows rows\n";
echo "  " . number_format(filesize($outPath)) . " bytes\n";
