// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homework-list/HomeworkList.tsx": () => import("../components/mockups/homework-list/HomeworkList.tsx")
};
